openapi: 3.0.0
info:
  title: Project Documentation API
  description: API endpoint to generate project documentation using a specified model and project path.
  version: 1.0.0

paths:
  /api/get-project-documentation:
    post:
      summary: Generate project documentation
      description: Generate project documentation based on a specified directory path and selected model.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                project_path:
                  type: string
                  description: "Absolute path to the project directory."
                  example: "/path/to/project"
                model:
                  type: string
                  description: "The model to use for documentation generation. Available models can be fetched using another endpoint."
                  example: "selected_model_name"
      responses:
        "200":
          description: Documentation generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Documentation generated successfully."
                  documentation_content:
                    type: string
                    description: "Generated documentation content."
                    example: "Generated documentation content here..."
        "400":
          description: Bad request - missing or invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Project directory path is required."
        "500":
          description: Server error during documentation generation
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error generating documentation: [error message]"
